### ISSUE TITLE
configuration needs to be in two folders

### ISSUE THREAD

**Issue by mathse** [imcf/auto-tx#2]
both config.common.xml and HOSTNAME.xml need to bei in C:\Tools\AutoTx\conf AND C:\Tools\AutoTx
only this way the service will start up

**Comment by mathse** [comment]
#1 related problem

**Comment by mathse** [comment]
not reproducable

**Comment by ehrenfeu** [comment]
Hi @mathse,

I cannot reproduce this on my side - my installations (nowadays) only have their configuration files in the `conf` subdirectory. Since the configuration location was changed recently there might be the chance this has not yet been reflected in all code locations, but for the core service itself I'm pretty sure that has been covered.

Let me know (i.e. re-open this issue) if you come across this issue again and have a way to reproduce!

Cheers,
Niko
